# Ensure very large files can be stored in these paths
# dot (.) means project directory
path:
  data: ./data/
  processed: ./processed/
  models: ./saved_models/

training:
  filtering:
    fraction:
        training: 1.
        validation: .3
    power_measure: line_flux_integral # Column to use for filtering data to training
  target:
    smoothing_fwhm: 0 # FWHM in arcsec of Gaussian for smoothing segmap. 7 according to data description, 0 = no smoothing.
    min_value: .1 # Minimum voxel value in final segmentmap used for training
    padding: 0.5 # Padding around minor axis as relative length of major axis. 0 is X-shape segmentmap, 1 means full cylinder
  cube_size:
    spatial: 32
    freq: 32

torch:
  num_workers: 0 # Ignored if CPU is used, larger values require more RAM
