# Ensure very large files can be stored in these paths
# dot (.) means project directory
path:
  data: ./data/
  processed: ./processed/
  models: ./saved_models/

training:
  filtering:
    fraction:
        training: 1.
        validation: .3
    power_measure: line_flux_integral # Column to use for filtering data to training
  target:
    smoothing_fwhm: 0 # FWHM in arcsec of Gaussian for smoothing segmap. 7 according to data description, 0 = no smoothing.
    min_value: .1 # Minimum voxel value in final segmentmap used for training
    padding: 1 # Padding around minor axis as relative length of major axis. 0 is X-shape segmentmap, 1 means full cylinder
  cube_size:
    spatial: 32
    freq: 32
  save_plots: True

downstream:
  calibration:
    hi_size:
      coefficient: 0.48
      intercept: 7.57

constants:
  speed_of_light: 299792.458
  h1_rest_freq: 1420000000.0

scoring:
  threshold:
    'pos': .3
    'hi_size': .3
    'line_flux_integral': .1
    'central_freq': .3
    'pa': 10.
    'i': 10.
    'w20': .3

torch:
  num_workers: 0 # Ignored if CPU is used, larger values require more RAM

characteristic_parameters:
  - ra
  - dec
  - hi_size
  - line_flux_integral
  - central_freq
  - pa
  - i
  - w20

hyperparameters:
  threshold: 0.5