# Ensure very large files can be stored in these paths
# dot (.) means project directory
path:
  data: ./data/
  processed: ./processed/

preprocessing:
  min_axis_pixels: 0.5



torch:
  num_workers = 0 # Ignored if CPU is used, larger values require more RAM
