# Ensure very large files can be stored in these paths
# dot (.) means project directory
path:
  data: ./data/
  processed: ./processed/
  models: ./saved_models/

data:
  splitsize: 60
  memory_batches: 20

segmentation:
  size: dev_s
  limit_files: null
  model_name: resnet18
  filtering:
    training: null
    validation: null
    power_measure: line_flux_integral # Column to use for filtering data to segmentation
  target:
    smoothing_fwhm: 0 # FWHM in arcsec of Gaussian for smoothing segmap. 7 according to data description, 0 = no smoothing.
    min_value: .1 # Minimum voxel value in final segmentmap used for segmentation
    padding: 1 # Padding around minor axis as relative length of major axis. 0 is X-shape segmentmap, 1 means full cylinder
  cube_size:
    spatial: 32
    freq: 32
  save_plots: False
  augmentation: True
  batch_size: 128
  robust_validation: False

downstream:
  sofia:
    param_file: /pipeline/SoFiA_parameters.txt
  calibration:
    hi_size:
      coefficient: 1 # 0.48
      intercept: 0 # 7.57

constants:
  speed_of_light: 299792.458
  h1_rest_freq: 1420000000.0

scoring:
  threshold:
    'pos': .3
    'hi_size': .3
    'line_flux_integral': .1
    'central_freq': .3
    'pa': 10.
    'i': 10.
    'w20': .3

characteristic_parameters:
  - ra
  - dec
  - hi_size
  - line_flux_integral
  - central_freq
  - pa
  - i
  - w20

hyperparameters:
  threshold: 0.5
  fp_penalty: 1

traversing:
  fits_file: null
  checkpoint: resnet18-15-epoch=109-val_loss=0.67.ckpt
  gpu_memory_max: 7000